# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0c1c6b2f99493936a4a423145a0cf6b"
name = "central-de-reservas"
application_url = "https://central.portugalmeandyou.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_draft_orders,write_files,read_metaobjects,write_app_proxy"

[auth]
redirect_urls = [ "https://central.portugalmeandyou.com/auth/callback" ]

[app_proxy]
url = "/app-proxy/pmy"
prefix = "apps"
subpath = "pmy-central"

[webhooks]
api_version = "2026-04"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false
